---
id: amazon_vpc_flow
name: Amazon VPC Flow Logs
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/amazon_vpc_flow/package.svg
description: |
  [Amazon VPC Flow Logs](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html)
  capture information about the IP traffic going to and from network interfaces
  in your VPC. This package provides utilities for parsing and mapping VPC Flow
  Log data to OCSF Network Activity events.

  ## Operators

  - `amazon_vpc_flow::parse` - Parse with custom header (field names as argument)
  - `amazon_vpc_flow::parse_v2` - Parse default AWS format (14 fields)
  - `amazon_vpc_flow::to_ocsf` - Map to OCSF Network Activity (class 4001)

categories:
  - sources
  - security

inputs:
  s3-bucket-url:
    name: S3 Bucket URL
    description: |
      The S3 URL path containing VPC Flow Log files.
    default: "s3://your-bucket/AWSLogs/**.log.gz"
  remove-inputs:
    name: Remove Files After Importing
    description: |
      Whether to remove files after processing them. Possible values are 'true' or 'false'.
    default: "false"
