id: abusech-sslbl
name: SSLBL
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/abusech-sslbl/package.svg
description: |
  The [SSL Blocklist (SSLBL)](https://sslbl.abuse.ch/) is a project of abuse.ch
  that identifies and tracks SSL certificates used by malware or botnet C&C
  servers.

  This package provides a lookup table containing SHA1 hashes of blacklisted
  certificates, automatically refreshed hourly from the abuse.ch API. Security
  teams can use this context to detect and block malicious SSL/TLS connections
  by enriching network traffic logs with certificate reputation data.
categories:
- contexts

inputs:
  refresh-interval:
    name: Time between context updates
    description: |
      The duration between updates that fetch the SSLBL database via the API.
    default: 1h

contexts:
  sslbl:
    type: lookup-table
    description: |
      A table that is keyed by SHA1 hashes of SSL certificates on the SSL
      blocklist.

examples:
  - name: Enrich Suricata TLS logs with SSLBL domains
    description: |
      Enriches the certificate SHA1 fingerprint from Suricata TLS logs with the
      SSLBL data.
    definition: |
      subscribe "suricata"
      where @name == "suricata.tls"
      sha1 = tls.fingerprint.replace(":", "")
      context::enrich "sha1", key=sslbl

  - name: Display top-10 listing reasons
    description: |
      Shows a bar chart of the top-10 reasons why a certificate is in the
      dataset.
    definition: |
      context::inspect "sslbl"
      this = value
      top reason
      head
      chart_bar x=reason, y=count
