id: foxio
name: FoxIO JA4+
author: Tenzir
author_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/foxio/package.svg

description: |
  The [FoxIO JA+ Database](https://ja4db.com/) provides context for various JA+
  fingerprints, such as operating system, device, library, user agent.

  This package provides multiple contexts for enrichment, each of which contains
  a subset of the JA4+ database for a particular JA4+ type and a corresponding
  example that periodically refreshes the context.
categories:
- contexts

