id: sysmon
name: Sysmon
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/author.svg
package_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/sysmon/package.svg
description: |
  [Sysmon](https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon)
  (System Monitor) is a Windows system service and device driver that logs
  detailed activity—process creation, network connections, file changes, and
  more—to the Windows Event Log.

  This package provides operators that parse Sysmon XML events and map them to
  OCSF.
categories:
- mappings
