id: abusech-feodo
name: Feodo Abuse Blocklist
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/abusech-feodo/package.svg

description: |
  [Feodo Tracker](https://feodotracker.abuse.ch/) is a project of abuse.ch with
  the goal of sharing botnet C&C servers associated with Dridex, Emotet (aka
  Heodo), TrickBot, QakBot (aka QuakBot / Qbot) and BazarLoader (aka
  BazarBackdoor). It offers various blocklists, helping network owners to
  protect their users from these banking trojans and malware families.

  This package provides a lookup table context that automatically updates hourly
  with the latest aggressive IP blocklist, enabling real-time threat detection
  and prevention against known botnet infrastructure.
categories:
- contexts

contexts:
  feodo:
    type: lookup-table
    description: A table that contains the elements of the feodo IP blocklist.

examples:
  - name: Enrich Feodo
    description: Evaluate the `src_ip` field of the input data against the Feodo IP Blocklist.
    definition: |
      export
      context::enrich "feodo", key=dst_ip
