---
id: amazon
name: Amazon Web Services
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/amazon/package.svg
description: |
  This package provides integrations for Amazon Web Services (AWS):

  ## VPC Flow Logs

  [Amazon VPC Flow Logs](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html)
  capture information about the IP traffic going to and from network interfaces
  in your VPC.

  Operators:
  - `amazon::vpc_flow::parse` - Parse CloudWatch events with custom header
  - `amazon::vpc_flow::parse_v2` - Parse default AWS format (14 fields)
  - `amazon::vpc_flow::parse_v7_ecs` - Parse v7 format with ECS fields (24 fields)
  - `amazon::vpc_flow::to_ocsf` - Map to OCSF Network Activity (class 4001)

  ## Security Lake

  [Amazon Security Lake](https://aws.amazon.com/security-lake/) automatically
  centralizes security data from cloud, on-premises, and custom sources.

  This package provides pipelines for writing OCSF events to Amazon Security
  Lake using the S3-based ingestion format.

  *NOTE*: Before you can write events to the Security Lake, you must configure
  a *custom source* per event type in Security Lake and ensure the Tenzir Node
  has write permissions to the S3 bucket in the respective source directory. The
  package assumes that you adhere to the Tenzir naming scheme `tnz-ocsf-XXXX` where
  `XXXX` is the class UID of an OCSF event class.

  Operators:
  - `amazon::security_lake::cast` - Cast OCSF events for Security Lake compatibility
  - `amazon::security_lake::send` - Send OCSF events to Security Lake

categories:
  - sources
  - destinations
  - security

inputs:
  # VPC Flow Logs inputs
  s3-bucket-url:
    name: S3 Bucket URL
    description: |
      The S3 URL path containing VPC Flow Log files.
    default: "s3://your-bucket/AWSLogs/**.log.gz"
  remove-inputs:
    name: Remove Files After Importing
    description: |
      Whether to remove files after processing them. Possible values are 'true' or 'false'.
    default: "false"
  # Security Lake inputs
  input-topic:
    name: Input topic
    description: Topic to subscribe to for OCSF events
    default: ocsf
  bucket-name:
    name: S3 bucket name
    description: The name of the S3 bucket in Security Lake (e.g., `aws-security-data-lake-eu-west-2-lake-abcdefghijklmnopqrstuvwxyz1234`
  region:
    name: AWS Region
    description: AWS region where the Security Lake is deployed
  account-id:
    name: AWS Account ID
    description: The ID of the AWS account that hosts the Security Lake instance.
  external-id:
    name: AWS External ID
    description: The external ID for all custom sources.
  timeout:
    name: Timeout
    description: Timeout for writing to Security Lake
    default: 5m
