---
id: amazon
name: Amazon Web Services
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/amazon/package.svg
description: |
  This package provides integrations for Amazon Web Services (AWS):

  ## VPC Flow Logs

  [Amazon VPC Flow Logs](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html)
  capture information about the IP traffic going to and from network interfaces
  in your VPC.

  Operators:
  - `amazon::vpc_flow::parse` - Parse CloudWatch events with custom header
  - `amazon::vpc_flow::parse_v2` - Parse default AWS format (14 fields)
  - `amazon::vpc_flow::parse_v7_ecs` - Parse v7 format with ECS fields (24 fields)
  - `amazon::vpc_flow::to_ocsf` - Map to OCSF Network Activity (class 4001)

  ## Route 53 Resolver Query Logs

  [Amazon Route 53 Resolver Query Logs](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-query-logs.html)
  log DNS queries that originate in your VPCs.

  Operators:
  - `amazon::route53::to_ocsf` - Map to OCSF DNS Activity (class 4003)

  ## Security Lake

  [Amazon Security Lake](https://aws.amazon.com/security-lake/) automatically
  centralizes security data from cloud, on-premises, and custom sources.

  This package provides pipelines for writing OCSF events to Amazon Security
  Lake using the S3-based ingestion format.

  *NOTE*: Before you can write events to the Security Lake, you must configure
  a *custom source* per event type in Security Lake and ensure the Tenzir Node
  has write permissions to the S3 bucket in the respective source directory. The
  package assumes that you adhere to the Tenzir naming scheme `tnz-ocsf-XXXX` where
  `XXXX` is the class UID of an OCSF event class.

  Operators:
  - `amazon::security_lake::cast` - Cast OCSF events for Security Lake compatibility
  - `amazon::security_lake::send` - Send OCSF events to Security Lake

categories:
  - sources
  - destinations
  - mappings
