id: zeek
name: Zeek
author: Tenzir
author_icon: https://github.com/tenzir.png
package_icon: https://raw.githubusercontent.com/tenzir/library/main/zeek/package.png

description: |
  The Zeek package provides various options to onboard Zeek logs.

inputs:
  listen-endpoint:
    name: Listen Endpoint
    description: A TCP endpoint where Zeek sends its logs.
    type: string
    default: 127.0.0.1:5555
  log-file:
    name: Log File Path
    description: The path to the Zeek log to read.
    type: string
  log-format:
    name: Log Format
    description: |
      The log format that is configured in your Zeek deployment (`json` or
      `tsv`).
    type: string
    default: json

pipelines:
  onboard-from-file:
    name: Onboard Zeek Logs from a File
    description: Connects a Zeek data source on the network.
    definition: |
      // tql2
      load_file {{ inputs.log-file }}
      read_zeek_{{ inputs.log-format }}
      publish "zeek"
    disabled: false

  onboard-from-tcp-socket:
    name: Onboard Zeek Logs via TCP
    description: Connects a Zeek data source on the network.
    definition: |
      // tql2
      legacy "from tcp://{{ inputs.listen-endpoint }} read zeek-{{ inputs.log-format }}"
      publish "zeek"
    disabled: true

snippets:
  - name: Zeek log volume from the last 3 hours
    description: |
      A line chart displaying how many Zeek events arrived in the last 3 hours.
    definition: |
        // tql2
        metrics "operator"
        let $ts = now() - 3h
        where timestamp > $ts
        where pipeline_id == "zeek/onboard-from-interface" or pipeline_id == "zeek/onboard-from-file"
        where source == true
        legacy "summarize bytes=sum(output.approx_bytes), duration=sum(duration) by timestamp resolution 2 min"
        this = {
          timestamp: timestamp,
          ingress_per_second: bytes / duration.as_secs(),
        }
        | sort timestamp
        | legacy "chart area"
