id: zeek
name: Zeek
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/zeek/package.svg
categories:
- sources
- mappings

description: |
  [Zeek](https://zeek.org) is an open-source network security monitor that
  provides rich logs about network activity.

  This package provides pipelines to onboard Zeek logs, as well as mapping
  pipelines that translate Zeek logs to OCSF events.

inputs:
  url:
    name: URL
    description: The URL to the Zeek logs.
    type: string
    default: file:///path/to/zeek/logs/**/*.log
  file-format:
    name: Zeek log format
    description: |
      The format of the Zeek logs. Either `json` or `tsv`.
    type: string
    default: tsv
