id: sophos
name: Sophos
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/sophos/package.svg
description: |
  The [Sophos](https://sophos.com) package onboards data from various [Sophos
  APIs](https://developer.sophos.com/apis). OCSF mapping examples create the respective findings.
categories:
- sources
- mappings

