id: sophos
name: Sophos
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/sophos/package.svg
description: |
  The [Sophos](https://sophos.com) package onboards data from various [Sophos
  APIs](https://developer.sophos.com/apis). OCSF mapping pipelines create the respective findings.
categories:
- sources
- mappings

inputs:
  poll-frequency:
    name: The poll frequency for the SIEM Integration API
    description: |
      How to often call the Sophos API in seconds
    default: 60
  client-id:
    name: Client ID
    description: |
      The Client ID as described at https://developer.sophos.com/getting-started-tenant.
    #default: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  client-secret:
    name: Client Secret
    description: |
      The Client Secret as described at https://developer.sophos.com/getting-started-tenant.
    #default: Basic <Base64>

# TODO: the two onboarding pipelines differ only in the API endpint that they
# call. To date, Tenzir's HTTP loader doesn't support pagination, which is why
# we use Python to workaround that.
examples:
  - name: Tap into high-severity events
    description: |
      Filter out high-severity events and project key columns.
    definition: |
      subscribe "sophos"
      where @name == "sophos.event" and severity == "high"
      select user_id, endpoint_type, type, source, name, location

  - name: Show the top threats
    description: |
      Show once per day the top values of the field `threat`.
    definition: |
      subscribe "sophos"
      where @name == "sophos.alert" and threat != null
      every 1d {
        top threat
      }
