id: sophos
name: Sophos
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/sophos/package.svg
description: |
  The [Sophos](https://sophos.com) package onboards data from various [Sophos
  APIs](https://developer.sophos.com/apis). OCSF mapping pipelines create the respective findings.
categories:
- sources
- mappings

inputs:
  poll-frequency:
    name: The poll frequency for the SIEM Integration API
    description: |
      How to often call the Sophos API in seconds
    default: 60
  client-id:
    name: Client ID
    description: |
      The Client ID as described at https://developer.sophos.com/getting-started-tenant.
    #default: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  client-secret:
    name: Client Secret
    description: |
      The Client Secret as described at https://developer.sophos.com/getting-started-tenant.
    #default: Basic <Base64>

