---
id: suricata
name: Suricata
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/author.svg
package_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/suricata/package.svg
description: |
  [Suricata](https://suricata.io) is an open-source network monitor and
  threat detection tool.

  This package makes it easy to onboard EVE JSON logs that Suricata generates.

inputs:
  eve-path:
    name: Suricata EVE JSON Output
    description: |
      The path configured in Suricata for writing EVE JSON.
    type: string
    default: /var/lib/suricata/eve.sock

pipelines:
  publish-suricata:
    name: Publish Suricata EVE JSON
    description: |
      Publishes Suricata events read from the configured EVE JSON Output on the
      `suricata` topic.
    restart-on-error: true
    definition: |
      // tql2
      load_file "{{ inputs.eve-path }}", follow=true
      read_suricata
      publish "suricata"

  import-suricata:
    name: Import Suricata
    description: |
      Persist events published on the topic `suricata`.
    disabled: true
    definition: |
      // tql2
      subscribe "suricata"
      import

examples:
  - name: Today's Alerts
    description: |
      View all Suricata alerts persisted in the last day.
    definition: |
      // tql2
      export
      where @name == "suricata.alert"
      let $ts = now() - 1d
      where @import_time > $ts
