id: suricata
name: Suricata
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/suricata/package.svg
categories:
- sources
- mappings
description: |
  [Suricata](https://suricata.io) is an open-source network monitoring and
  threat detection tool.

  This package provides pipelines to onboard Suricata logs, as well as mapping
  pipelines that translate Suricata EVE JSON to OCSF events.

inputs:
  eve-url:
    name: Suricata EVE JSON Output
    description: |
      The path configured in Suricata for writing EVE JSON.
    type: string
    default: /var/lib/suricata/eve.sock
