id: slack
name: Send to Slack
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/slack/package.svg

description: |
  The [Slack](https://slack.com) package makes it easy to send data from a
  pipeline to a Slack channel using incoming webhooks, enabling real-time
  security alerts and notifications. Configure the package with your Slack app's
  webhook URL to automatically forward critical events, detection results, or
  aggregated metrics directly to your team's communication channels. This
  integration supports custom message formatting and allows security teams to
  stay informed about important events without leaving their collaboration
  workspace.
categories:
- destinations

inputs:
  webhook-url:
    name: Webhook URL
    description: |
      Follow [Slack's documentation](https://api.slack.com/messaging/webhooks)
      for a step-by-step guide to obtain an URL for your app.
    type: string
    default: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX

