id: slack
name: Send to Slack
author: Tenzir
author_icon: https://github.com/tenzir.png
package_icon: https://github.com/slackhq.png

description: |
  This package sets up a pipeline that forwards events to a Slack channel.

inputs:
  webhook-url:
    name: Webhook URL
    description: |
      This package requires an incoming webhook URL from a Slack app. Follow
      Slack's documentation for a step-by-step guide to obtain an URL for your
      app: https://api.slack.com/messaging/webhooks
    type: string
    default: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX

pipelines:
  send-to-slack:
    name: Send to Slack
    description: |
      Forwards all events arriving on the topic `slack` to Slack.
    definition: |
      // Slack requires every message to arrive in a JSON body in the format
      // `{text: "<message>"}`. To achieve that, we just write the content out
      // line by line and then read it back in, which gives us a human-readable
      // dump of the events in Slack, no matter what form they were in before.
      subscribe slack
      | write lines
      | read lines
      | put text=line
      | batch 1
      | to http POST "{{ inputs.webhook-url }}" write json

snippets:
  - name: Say Hello in Slack
    description: |
      Sends the message "Hello, world! 👋" to Slack.
    definition: |
      // tql2
      from { message: "Hello, world! 👋" }
      publish "slack"
