id: slack
name: Send to Slack
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/author.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/slack/package.svg

description: |
  The [Slack](https://slack.com) package makes it easy to send data from a
  pipeline to a Slack channel. The package requires an incoming webhook URL from
  a Slack app.

inputs:
  webhook-url:
    name: Webhook URL
    description: |
      Follow [Slack's documentation](https://api.slack.com/messaging/webhooks)
      for a step-by-step guide to obtain an URL for your app.
    type: string
    default: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX

pipelines:
  send-to-slack:
    name: Send to Slack
    description: |
      Forwards all events arriving on the topic `slack` to Slack.
    definition: |
      // Slack requires every message to arrive in a JSON body in the format
      // `{text: "<message>"}`. To achieve that, we just write the content out
      // line by line and then read it back in, which gives us a human-readable
      // dump of the events in Slack, no matter what form they were in before.
      subscribe slack
      | write lines
      | read lines
      | put text=line
      | batch 1
      | to http POST "{{ inputs.webhook-url }}" write json

examples:
  - name: Say Hello in Slack
    description: |
      Sends the message "Hello, world! 👋" to Slack.
    definition: |
      // tql2
      from { message: "Hello, world! 👋" }
      publish "slack"
