id: abusech-threatfox
name: ThreatFox
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/abusech-threatfox/package.svg

description: |
  [ThreatFox](https://threatfox.abuse.ch/) is a free platform from abuse.ch with
  the goal of sharing indicators of compromise (IOCs) associated with malware
  with the infosec community, AV vendors and threat intelligence providers. The
  platform collects and validates IOCs from vetted researchers and automatically
  tracks malware campaigns across various threat families. This package provides
  multiple lookup table contexts for different IOC types (IPs, domains, URLs,
  and hashes) with pipelines that periodically refresh from the ThreatFox API,
  enabling automated threat detection and enrichment across your security data.

categories:
- contexts

inputs:
  auth-key:
    name: Threatfox API Auth Key
    description: |
      The key to use for authentication with the Threatfox API.
    type: string

  days:
    name: Number of days
    description: |
      Number of days to filter IOCs for (min: 1, max: 7)
    type: string
    default: 3

  refresh-interval:
    name: Time between context updates
    description: |
      The duration between context updates that fetch the ThreatFox database via
      the API.
    type: string
    default: 1h

contexts:
  threatfox-ipports:
    type: lookup-table
    description: |
      The subset of the ThreatFox IOC Database for (IP, port) tuples.
      The lookup key has type `<ip: ip, port: uint64>`, e.g., `{ip: "1.2.3.4",
      port: 80}`.

  threatfox-domains:
    type: lookup-table
    description: |
      The subset of the ThreatFox IOC Database for domains.
      The lookup key has type `string`, e.g.,`evil.com`.

  threatfox-urls:
    type: lookup-table
    description: |
      The subset of the ThreatFox IOC Database for URLs.
      The lookup key has type `string`, e.g., `https://evil.com/malware.exe`.

  threatfox-hashes:
    type: lookup-table
    description: |
      The subset of the ThreatFox IOC Database for hashes (MD5, SHA1, SHA256).
      The lookup key has type `string`, e.g.,
      `2d29a1c2e5c6d26bc103343637562205`.
