id: misp
name: MISP
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/misp/package.svg

description: |
  MISP (Malware Information Sharing Platform) is an open-source software
  solution for gathering, sharing, storing, and correlating Indicators of
  Compromise from cyberattacks, threat intelligence, and financial fraud.

  This package provides pipelines to fetch MISP events and normalize them
  to OCSF Inventory Info events.

categories:
- source

inputs:
  api-key-secret:
    name: API key secret name
    description: |
      Your MISP API key ID
    default: MISP_API_KEY

  refresh-interval:
    name: Context update interval
    description: |
      The duration between context updates that fetch attributes from the API.
    default: 1h

  base-url:
    name: Base API endpoint URL
    description: |
      The base URL of the MISP instance.
    default: https://misp.local
