id: splunk
name: Splunk
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/author.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/splunk/package.svg

description: |
  A package to send data to Splunk via the HTTP Event Collector (HEC).

inputs:
  splunk_token:
    name: Splunk token
    description: The token for authenticating to the Splunk instance.
    type: string

  events_topic:
    name: Incoming events topic
    description: |
      The topic to subscribe to. This allows other pipelines to send data to
      Splunk by publishing to that topic.
    type: string
    default: splunk

  splunk_host:
    name: Splunk host
    description: The hostname or IP address of the Splunk instance.
    type: string
    default: localhost

  splunk_port:
    name: Splunk port
    description: The port where Splunk HEC listens.
    type: string
    default: 8088

  event_index:
    name: Splunk event index
    description: The name of the index where Splunk stores the events.
    type: string
    default: main

pipelines:
  send_to_splunk:
    name: Send data to Splunk
    description: Send data to a Splunk instance.
    definition: |
      subscribe {{ inputs.events_topic }}
      | fluent-bit
          splunk
          host={{ inputs.splunk_host }}
          port={{ inputs.splunk_port }}
          tls=on
          tls.verify=off
          splunk_token={{ inputs.splunk_token }}
          event_index={{ inputs.event_index }}
