id: splunk
name: Splunk
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/splunk/package.svg
description: |
  This package enables seamless data export to [Splunk](https://www.splunk.com)
  via the HTTP Event Collector (HEC), allowing you to integrate Tenzir pipelines
  with your existing Splunk infrastructure.

  Configure the package with your HEC endpoint and token to stream processed
  security events, metrics, or any structured data directly into Splunk indexes.
  The integration supports both cloud and on-premises Splunk deployments, making
  it easy to leverage Tenzir's data processing capabilities while maintaining
  your Splunk-based analytics and alerting workflows.
categories:
- destinations

inputs:
  splunk_token:
    name: Splunk token
    description: The token for authenticating to the Splunk instance.
    type: string

  events_topic:
    name: Incoming events topic
    description: |
      The topic to subscribe to. This allows other pipelines to send data to
      Splunk by publishing to that topic.
    type: string
    default: splunk

  splunk_url:
    name: URL for the Splunk Indexer
    description: URL for the Splunk Indexer
    type: string
    default: https://localhost:8080

  event_index:
    name: Splunk event index
    description: The name of the index where Splunk stores the events.
    type: string
    default: main

pipelines:
  send_to_splunk:
    name: Send data to Splunk
    description: Send data to a Splunk instance.
    definition: |
      subscribe "{{ inputs.events_topic }}"
      to_splunk "{{ inputs.splunk_url }}",
        hec_token="{{ inputs.splunk_token }}",
        index="{{ inputs.event_index }}",
        skip_peer_verification = true
