name: Tenzir
author: tenzir

description: |
  A package with a context that maps two-letter country codes to emojis.

contexts:
  flags:
    type: lookup-table
    description: A lookup table that maps two-letter cuntry codes to emoji flags.
    data: mappings

snippets:
  - name: Enrich Suricata alerts with country flags.
    description: |
      Take Suricata alerts, enrich their IP addresses with a GeoIP context, and
      then replace the country codes with emoji flags.
    definition: |
      export
      | where #schema == "suricata.alert"
      | enrich geo --fields :ip
      | enrich flags --fields :string

data:
  mappings:
    - country: AD
      flag: 🇦🇩
    - country: AE
      flag: 🇦🇪
