id: zscaler-internet-access
name: Zscaler Internet Access
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/zscaler-internet-access/package.svg
description: |
  [Zscaler Internet Access (ZIA)](https://www.zscaler.com/products-and-solutions/zscaler-internet-access)
  is a cloud-native secure web gateway that provides comprehensive security for
  users accessing the internet from any location or device.

  This package enables ingestion and processing of ZIA logs, including web
  traffic, firewall, DNS, and tunnel events, providing visibility into your
  organization's internet activity and security posture. The package includes
  OCSF mapping pipelines that transform ZIA events into standardized formats,
  making it easy to correlate Zscaler data with other security tools in your
  environment.
categories:
- mappings
- sources

inputs:
  listen-endpoint:
    name: Listen Endpoint
    description: A TCP endpoint where Zscaler NSS sends its logs.
    type: string
    default: 0.0.0.0:8080

  file-url:
    name: Log file URL
    description: A URL at which one or more files with Zscaler logs can be found.
    type: string

  file-watch:
    name: Log file URL watch
    description: Whether to watch the file url for new files.
    type: boolean
