id: aws-vpcflow
name: AWS VPC Flow Logs
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/aws-vpcflow/package.svg

description: |
  AWS VPC Flow Logs capture information about IP traffic going to and from
  network interfaces in your VPC. This package provides utilities for
  ingesting, parsing, and analyzing VPC Flow Log data.

  This package provides:
  - Raw VPC Flow Log events on the `aws` topic as `aws.vpc_flow` events
  - OCSF-formatted network activity events on the `ocsf` topic as `ocsf.network_activity` events

  To use this package, you must configure your AWS VPC to log to S3 in text
  format as described in the [AWS documentation](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-s3.html).

categories:
- connectors

inputs:
  s3-bucket-url:
    name: S3 Bucket URL
    description: |
      The S3 URL path containing VPC Flow Log files.
    default: "s3://your-bucket/AWSLogs/**.log.gz"
  remove-inputs:
    name: Remove Files After Importing
    description: |
      Whether to remove files after processing them. Possible values are 'true' or 'false'.
    default: "false"

examples:
  - name: Export to Amazon Security Lake
    description: |
      Export OCSF Network Activity events to Amazon Security Lake.
      Requires a Security Lake with a custom source configured for NETWORK_ACTIVITY input.
      Also consider using our "Security Lake" package, which includes this and
      similar pipelines for many OCSF types.
    definition: |
      let $s3_uri = "s3://your-security-lake-bucket/ext/your-prefix"
      let $s3_region = "your-region"
      let $s3_account_id = "123456789012"

      subscribe "ocsf"
      where @name == "ocsf.network_activity"
      to_amazon_security_lake $s3_uri,
        region=$s3_region,
        account_id=$s3_account_id
