id: cisco-umbrella
name: Cisco Umbrella
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/cisco-umbrella/package.svg
description: |
  The [Cisco Umbrella](https://docs.umbrella.com/deployment-umbrella/docs/welcome-to-cisco-umbrella) package
  onboards [DNS Log data](https://docs.umbrella.com/deployment-umbrella/docs/dns-log-formats) from
  a [Cisco Umbrella S3 Bucket](https://docs.umbrella.com/deployment-umbrella/docs/log-management#logging-to-amazon-s3).
categories:
- sources
- mappings

inputs:
  aws-access-key-id:
    name: AWS Access Key ID
    description: |
      The AWS access key id.
    default: "XXXXXXXXXXXXXXXXXXXX"
  aws-secret-access-key:
    name: AWS Secret Access Key
    description: |
      The AWS secret access key.
    default: "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
  aws-region:
    name: AWS Region
    description: |
      The AWS Region of the log bucket.
    default: eu-central-1
  s3-url:
    name: S3 URL
    description: |
      The S3 URL in which to look for files.
    default: "s3://cisco-managed-eu-central-1/0000000_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  poll-frequency:
    name: The poll frequency for the SIEM Integration API
    description: |
      How to often to check for new files
    default: 15m
