id: demo-data-generator
name: Demo Data Generator
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/author.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/demo-data-generator/package.svg

description: |
  This package provides a live Zeek and Suricata event feed for demo purposes.
categories:
- sources

inputs:
  speed:
    name: Speed
    description: |
      A speed of 1.0 corresponds to a data velocity convenient for most demos.
    type: string
    default: 1.0

pipelines:
  zeek:
    name: Zeek Demo Data
    description: |
      Publishes a live demo data feed to the `zeek` topic.
    restart-on-error: 1min
    definition: |
      let $speed = {{ inputs.speed }}
      let $first = 2021-11-18T10:00:00Z
      let $last = 2021-11-19T01:00:00Z
      let $default = 3h
      let $period = $default / $speed
      let $factor = ($last - $first) / $period

      every $period {
        from {
          url: "https://storage.googleapis.com/tenzir-datasets/M57/zeek-all.log.zst",
        }
      }
      http url {
        decompress_zstd
        read_zeek_tsv
        where $first <= ts and ts <= $last
        sort ts
        delay ts, start=$first, speed=$factor
      }
      publish "zeek"

  suricata:
    name: Suricata Demo Data
    description: |
      Publishes a live demo data feed to the `suricata` topic.
    restart-on-error: 1min
    definition: |
      let $speed = {{ inputs.speed }}
      let $first = 2021-11-18T08:10:00Z
      let $last = 2021-11-18T08:38:00Z
      let $default = 30s
      let $period = $default / $speed
      let $factor = ($last - $first) / $period

      every $period {
        from {
          url: "https://storage.googleapis.com/tenzir-datasets/M57/suricata.json.zst",
        }
      }
      http url {
        decompress_zstd
        read_suricata
        head 30k
        where $first <= timestamp and timestamp <= $last
        sort timestamp
        // Drop some very frequent data to get a more even distribution.
        if @name == "suricata.dns" {
          if random() > 0.01 {
            discard
          }
        } else if @name == "suricata.tls" {
          if random() > 0.3 {
            discard
          }
        }
        delay timestamp, start=$first, speed=$factor
      }
      publish "suricata"
