id: demo-data-generator
name: Demo Data Generator
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/demo-data-generator/package.svg

description: |
  This package provides a live Zeek and Suricata event feed for demo purposes.
  It generates synthetic network security events based on realistic patterns,
  including DNS queries, HTTP traffic, SSL connections, and potential security
  alerts. The generated data is ideal for testing pipelines, developing
  detections, and demonstrating Tenzir's capabilities without requiring actual
  network traffic or production data.
categories:
- sources

inputs:
  speed:
    name: Speed
    description: |
      A speed of 1.0 corresponds to a data velocity convenient for most demos.
    type: string
    default: 1.0
