id: geo-open
name: Geo Open
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/author.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/geo-open/package.svg

description: |
  Free IP geolocation using Geo Open MMDB databases from CIRCL. Geo Open
  provides daily snapshots of IP-to-country and IP-to-ASN mappings in MaxMind
  database format. This package provides two contexts for IP enrichment:
  country-only lookups and combined country+ASN lookups.

categories:
- contexts

contexts:
  geo-open-country:
    type: geoip
    description: GeoIP context for country-only lookups using Geo Open data.

  geo-open-country-asn:
    type: geoip
    description: GeoIP context for country and ASN lookups using Geo Open data.

pipelines:
  update-geo-open-country-context:
    name: Update Geo Open Country context
    description: Fetches the latest country MMDB file daily.
    definition: |
      every 24h {
        from_http "https://cra.circl.lu/opendata/geo-open/mmdb-country/latest.mmdb" {
          context::load "geo-open-country"
        }
      }
    restart-on-error: 1h

  update-geo-open-country-asn-context:
    name: Update Geo Open Country ASN context
    description: Fetches the latest country+ASN MMDB file daily.
    definition: |
      every 24h {
        from_http "https://cra.circl.lu/opendata/geo-open/mmdb-country-asn/latest.mmdb" {
          context::load "geo-open-country-asn"
        }
      }
    restart-on-error: 1h

examples:
  - name: Enrich DNS Server IPs with Geo Data
    description: |
      Enriches DNS server IP addresses with country and ASN information using
      Geo Open data.
    definition: |
      from {
        server: 1.1.1.1,
      }, {
        server: 8.8.8.8,
      }, {
        server: 9.9.9.9,
      }
      context::enrich "geo-open-country-asn", key=server
