id: geo-open
name: Geo Open
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/geo-open/package.svg

description: |
  Free IP geolocation using Geo Open MMDB databases from CIRCL. Geo Open
  provides daily snapshots of IP-to-country and IP-to-ASN mappings in MaxMind
  database format. This package provides two contexts for IP enrichment:
  country-only lookups and combined country+ASN lookups.

inputs:
  enrich-input:
    name: Enrichment input topic
    description: |
      The name of the input topic used for OCSF event enrichment.
    default: ocsf

  enrich-output:
    name: Enrichment output topic
    description: |
      The name of the output topic used for OCSF event enrichment.
    default: ocsf-geo-open

categories:
- contexts

contexts:
  geo-open-country:
    type: geoip
    description: GeoIP context for country-only lookups using Geo Open data.

  geo-open-country-asn:
    type: geoip
    description: GeoIP context for country and ASN lookups using Geo Open data.

pipelines:
  update-geo-open-country-context:
    name: Update Geo Open Country context
    description: Fetches the latest country MMDB file daily.
    definition: |
      every 24h {
        from_http "https://cra.circl.lu/opendata/geo-open/mmdb-country/latest.mmdb" {
          context::load "geo-open-country"
        }
      }
    restart-on-error: 1h

  update-geo-open-country-asn-context:
    name: Update Geo Open Country ASN context
    description: Fetches the latest country+ASN MMDB file daily.
    definition: |
      every 24h {
        from_http "https://cra.circl.lu/opendata/geo-open/mmdb-country-asn/latest.mmdb" {
          context::load "geo-open-country-asn"
        }
      }
    restart-on-error: 1h

  enrich-ocsf-endpoints:
    name: Enrich OCSF events with GeoIP context
    description: Inspects `src_endpoint` and `dst_endpoint` to enrich them with GeoIP information.
    definition: |
      subscribe "{{ inputs.enrich-input }}"
      if src_endpoint?.ip? != null {
        context::enrich "geo-open-country-asn", key=src_endpoint.ip, into=_tmp
        if _tmp != null {
          if _tmp.country.iso_code != "None" {
            src_endpoint.location.country = _tmp.country.iso_code
          }
          src_endpoint.autonomous_system = {
            name: _tmp.country.AutonomousSystemOrganization,
            number: _tmp.country.AutonomousSystemNumber.int(),
          }
        }
        drop _tmp
      }
      if dst_endpoint?.ip? != null {
        context::enrich "geo-open-country-asn", key=dst_endpoint.ip, into=_tmp
        if _tmp != null {
          if _tmp.country.iso_code != "None" {
            dst_endpoint.location.country = _tmp.country.iso_code
          }
          dst_endpoint.autonomous_system = {
            name: _tmp.country.AutonomousSystemOrganization,
            number: _tmp.country.AutonomousSystemNumber.int(),
          }
        }
        drop _tmp
      }
      publish "{{ inputs.enrich-output }}"
    restart-on-error: 1min

examples:
  - name: Enrich DNS Server IPs with Geo Data
    description: |
      Enriches DNS server IP addresses with country and ASN information using
      Geo Open data.
    definition: |
      from {server: 1.1.1.1},
           {server: 8.8.8.8},
           {server: 9.9.9.9}
      context::enrich "geo-open-country-asn", key=server
  - name: Receive GeoIP-enriched OCSF events
    description: |
      Produces a feed of OCSF events with GeoIP information.
    definition: |
      subscribe "{{ inputs.enrich-output }}"
