id: geo-open
name: Geo Open
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/geo-open/package.svg

description: |
  Free IP geolocation using Geo Open MMDB databases from CIRCL, the Computer
  Incident Response Center Luxembourg. Geo Open provides daily snapshots of
  IP-to-country and IP-to-ASN mappings in MaxMind database format, offering a
  privacy-respecting alternative to commercial geolocation services.

  This package provides two GeoIP contexts for IP enrichment: country-only
  lookups for basic geographic attribution and combined country+ASN lookups for
  more detailed network analysis, with automatic daily updates to ensure
  accuracy.

inputs:
  enrich-input:
    name: Enrichment input topic
    description: |
      The name of the input topic used for OCSF event enrichment.
    default: ocsf

  enrich-output:
    name: Enrichment output topic
    description: |
      The name of the output topic used for OCSF event enrichment.
    default: ocsf-geo

categories:
- contexts

contexts:
  geo-open-country:
    type: geoip
    description: GeoIP context for country-only lookups using Geo Open data.

  geo-open-country-asn:
    type: geoip
    description: GeoIP context for country and ASN lookups using Geo Open data.

