id: winevent-uf
name: Windows EventLog UF
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/author.svg
#package_icon: https://raw.githubusercontent.com/tenzir/library/main/paloalto/package.svg

description: |
  This package integrates Windows Event logs collection via a Splunk Universal or Heavy Forwarder.

  Splunk Forwarders can send raw logs to Tenzir by adding the following stanza to the outputs.conf file:

    [tcpout:fastlane]
    server = <ip of Tenzir Node>:<Port>
    sendCookedData = false



pipelines:
  onboard-from-url:
    name: Onboard and parse raw Windows Event logs
    description: |
      foo
    definition: |
      let $patterns = {
        WIN_TIMESTAMP: "%{MONTHNUM2}/%{MONTHDAY}/%{YEAR} %{HOUR}:%{MINUTE}:%{SECOND} (AM|PM)",
      }

      read_lines split_at_regex="(\\r)?\n(?=[0-9]{2}/[0-9]{2})"
      slice begin=1
      unpack_1 = line.parse_grok("%{WIN_TIMESTAMP:timestamp}\n%{GREEDYDATA:rest}", pattern_definitions=$patterns)
      unpack_2 = unpack_1.?rest.split("Message=")
      this = {
        Timestamp: unpack_1.timestamp,
        ...unpack_2[0].parse_kv(field_split="\n", value_split="="),
        Message: unpack_2[1]
      }
