id: dcso-tie
name: DCSO TIE
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/dcso-tie/package.svg

description: |
  The [DCSO Threat Intelligence Engine
  (TIE)](https://docs.dcso.de/docs/tie/get-started/) provides premium threat
  intelligence feeds from Deutsche Cyber-Sicherheitsorganisation (DCSO), a
  leading European provider of threat intelligence services. DCSO delivers
  high-fidelity APT and threat intelligence with deep analysis of threats and
  campaigns, offering European sovereign intelligence sources for enhanced
  security operations.

  For detailed API documentation and IOC schema definitions, refer to the
  [DCSO TIE API documentation](https://docs.dcso.de/docs/tie/tiev3/ioc_schema_definition).

  This package provides the `dcso-tie` context for enrichment and
  pipelines that periodically update the feed, enabling real-time threat
  detection and intelligence-driven security workflows.

categories:
- sources

inputs:
  api-user-secret:
    name: API user ID secret name
    description: |
      Your DCSO TIE API user ID
    default: DCSO_TIE_API_USER

  api-key-secret:
    name: API key secret name
    description: |
      Your DCSO TIE API key
    default: DCSO_TIE_API_KEY

  refresh-interval:
    name: Context update interval
    description: |
      The duration between context updates that fetch IOCs from the API.
    default: 1h

  min-confidence:
    name: Minimum confidence level
    description: |
      The minimum confidence level for IOCs. Must be between 0 and 100, with
      0 being the least confident and 100 being the most confident.
    default: 0

  base-url:
    name: Base API endpoint URL
    description: |
      The base URL for the DCSO TIE API endpoint.
    default: "https://api.dcso.de/tie/v3"
