---
id: umbrella-ocsf
name: Umbrella OCSF Mappings
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/author.svg
package_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/umbrella-ocsf/package.svg
description: |
  [Umbrella](https://umbrella.cisco.com/) is modern cybersecurity made easy.

  This package converts all Umbrella DNS events published on the topic
  `tenzir.umbrella-dns` to OCSF and publishes the converted events on the topic
  `ocsf`.

pipelines:
  umbrella-dns-to-ocsf:
    name: Umbrella DNS to OCSF DNS Activity
    description: Maps CISCO Umbrella DNS logs to an OCSF DNS Activity event.
    restart-on-error: 5m
    disabled: false
    definition: |
      // tql2
      subscribe "tenzir.umbrella-dns"
      // (1) Move original event into dedicated field.
      this = { event: this }
      // (2) Assign some intermediate values for use in the next step, e.g., because
      //     they're used multiple times.
      activity_id = 1
      ...
      // (3) Populate the OCSF event.
      this = {
        // --- Classification (required) ---
        type_uid: 400301,
        severity_id: 1,
        class_uid: 4003,
        category_uid: 4,
        activity_id: activity_id,
        ...
        // --- Occurrence ---
        time: time(event.timestamp),
        // --- Context ---
        unmapped: event, // (4) Explicitly assign unmapped.
        ...
        // --- Primary ---
        src_endpoint: {
          ip: event.external_ip,
        },
        dst_endpoint: {
          ip: event.dest_ip,
          port: event.dest_port,
        },
        status_id: 1,
        rcode_id: rcode_id,
        rcode: rcode,
        query: query,
        answers: answers,
        ...
      }
      // (5) Drop all mapped fields, with the effect that the remaining fields remain
      //     in unmapped.
      drop(
        unmapped.id,
        ...
      )
      // (6) Assign a new schema name to the transformed event.
      @name = "ocsf.dns_activity"
      publish "ocsf"
