id: threatfox
name: ThreatFox
author: Tenzir
author_icon: https://github.com/tenzir.png
package_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/threatfox/package.svg

description: |
  [ThreatFox](https://threatfox.abuse.ch/) is a free platform from abuse.ch with
  the goal of sharing indicators of compromise (IOCs) associated with malware
  with the infosec community, AV vendors and threat intelligence providers.

  This package provides multiple contexts for enrichment, each of which contains
  a subset of the ThreatFox IOC database for a particular IOC type and a
  corresponding pipeline that periodically refreshes the context.

inputs:
  days:
    name: Number of days
    description: |
      Number of days to filter IOCs for (min: 1, max: 7)
    type: string
    default: 3

  refresh-interval:
    name: Time between context updates
    description: |
      The duration between context updates that fetch the ThreatFox database via
      the API.
    type: string
    default: 1 hour

contexts:
  threatfox-ipports:
    type: lookup-table
    description: |
      The subset of the ThreatFox IOC Database for (IP, port) tuples.
      The lookup key has type `<ip: ip, port: uint64>`, e.g., `{ip: "1.2.3.4",
      port: 80}`.

  threatfox-domains:
    type: lookup-table
    description: |
      The subset of the ThreatFox IOC Database for domains.
      The lookup key has type `string`, e.g.,`evil.com`.

  threatfox-urls:
    type: lookup-table
    description: |
      The subset of the ThreatFox IOC Database for URLs.
      The lookup key has type `string`, e.g., `https://evil.com/malware.exe`.

  threatfox-hashes:
    type: lookup-table
    description: |
      The subset of the ThreatFox IOC Database for hashes (MD5, SHA1, SHA256).
      The lookup key has type `string`, e.g.,
      `2d29a1c2e5c6d26bc103343637562205`.

pipelines:
  fetch-threatfox-ioc-database:
    name: Update ThreatFox context
    description: |
      A pipeline that periodically fetches the ThreatFox IOC database and
      publishes the feed to the `threatfox` topic.
    definition: |
      every {{ inputs.refresh-interval }}
        from https://threatfox-api.abuse.ch/api/v1/
          query=get_iocs
          days:={{ inputs.days }}
      | yield data[]
      // This is a hack that we need because there are no union types. We
      // roundtrip via the JSON parser which does per-event type inference for
      // us.
      | write json -c
      | read json --ndjson --precise
      | publish threatfox

  # We are currently creating one pipeline per IOC type. Once we have a more
  # powerful group operator, it would be nice to write some thing like
  # `group ioc_type { ... }` and then update the corresponding context
  # dynamically.
  populate-context-ipports:
    name: Update the ThreatFox context for (IP, port) tuples
    description: |
      A pipeline that puts (IP, port) tuples into the corresponding context.
    definition: |
      // tql2
      | subscribe "threatfox"
      | where ioc_type == "ip:port"
      | ioc = ioc.grok("%{IP:ip}:%{NUMBER:port}")
      | legacy "context update threatfox-ipports --key=ioc"

  populate-context-domains:
    name: Update the ThreatFox context for domains
    description: |
      A pipeline that puts domains into the corresponding context.
    definition: |
      // tql2
      | subscribe "threatfox"
      | where ioc_type == "domain"
      | legacy "context update threatfox-domains --key=ioc"

  populate-context-urls:
    name: Update the ThreatFox context for domains
    description: |
      A pipeline that puts domains into the corresponding context.
    definition: |
      // tql2
      | subscribe "threatfox"
      | where ioc_type == "url"
      | legacy "context update threatfox-domains --key=ioc"

  populate-context-hashes:
    name: Update the ThreatFox context for domains
    description: |
      A pipeline that puts domains into the corresponding context.
    definition: |
      // tql2
      | subscribe "threatfox"
      | where ioc_type.ends_with("hash")
      | legacy "context update threatfox-hashes --key=ioc"

snippets:
  - name: Enrich Zeek DNS logs with ThreatFox domains
    description: |
      Enriches Zeek DNS logs with the ThreatFox IOCs of type `domain`.
    definition: |
      subscribe zeek
      | where #schema == "zeek.dns"
      | enrich threatfox-domains --field=query

  - name: ThreatFox IOCs by confidence
    description: |
      Shows a bar chart that plots the number of IOCs per confidence level.
    definition: |
      from https://threatfox-api.abuse.ch/api/v1/
        query=get_iocs
        days:=7
      | yield data[]
      | summarize count(.) by confidence_level
      | sort confidence_level desc
      | chart bar

  - name: ThreatFox IOCs by type
    description: |
      Shows a bar chart that plots the number of IOCs per confidence level.
    definition: |
      from https://threatfox-api.abuse.ch/api/v1/
        query=get_iocs
        days:=7
      | yield data[]
      | top ioc_type
      | chart bar

  - name: Show all ThreatFox domains
    description: |
      Shows a table of all ThreatFox IOCs of type `domain`.
    definition: |
      context inspect threatfox-domains
      | yield data[]
