id: alphamountain
name: alphaMountain
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/alphamountain/package.svg

description: |
  [alphaMountain](https://alphamountain.ai) provides up-to-date domain and IP
  intelligence for cybersecurity investigational and protection platforms.

  This package provides the `alphamountain-threats` context for enrichment and
  pipelines that periodically update the feed.
categories:
- contexts

inputs:
  license:
    name: License key
    description: |
      Your alphaMountain batch API key.
    type: string

  refresh-interval:
    name: Time between context updates
    description: |
      The duration between context updates that fetch the alphaMountain database via
      the API.
    type: string
    default: 1h

  threat-expiry:
    name: Threats expire after
    description: |
      The time after which threats get removed from the context.
    type: string
    default: 7d

  min-risk:
    name: Minimum risk level
    description: |
      The minimum risk level for threats. Must be between 0.0 and 10.0, with
      0.0 being the most trusted, 5.0 being unknown, and 10.0 being the most
      malicious.
    type: string
    default: 8.5

contexts:
  alphamountain-threats:
    type: lookup-table
    description: |
      Threats from the alphaMountain database. The lookup key
      is of type `string` for hostnames and URLs, and `ip`
      for IP addresses.

  alphamountain-categories:
    type: lookup-table
    description: |
      Categories from the alphaMountain database.
      The lookup key is of type `string` for hostnames and URLs or `ip` for IP
      addresses.
