id: ocsf-osint
name: OCSF OSINT Enrichment
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/author.svg
package_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/ocsf-osint/package.svg

description: |
  TODO

categories:
- contexts

inputs:
contexts:
  ocsf-osint:
    type: lookup-table
    description: |
      A lookup table that contains IOCs in the form of [OCSF OSINT](https://schema.ocsf.io/1.5.0/objects/osint) objects.

pipelines:
  update-ocsf-osint-context:
    name: Update the OCSF OSINT Context
    description: |
      A pipeline that updates the `ocsf.osint` context.
    definition: |
      subscribe "ocsf.osint"
      context::update \
        "ocsf-osint",
        key=hostname,
        create_timeout={{ inputs.ioc-expiry }}

#  enrich-with-ocsf-osint:
#    name: Enriches OCSF events with the OCSF OSINT Context
#    description: |
#      A pipeline that enriches OCSF events with the OSINT objects from the
#      `ocsf.osint` context.
#    definition: |
#      subscribe "ocsf"
#      context::enrich \
#        "ocsf-osint",
#        ...
