id: ocsf-osint
name: OCSF OSINT Enrichment
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: |
  https://raw.githubusercontent.com/tenzir/library/main/ocsf-osint/package.svg

description: |
  This package provides a lookup table context for enriching OCSF events with
  OCSF [OSINT](https://schema.ocsf.io/1.5.0/objects/osint) objects, enabling
  threat intelligence integration within your security data pipeline. The OSINT
  context allows you to correlate events with known threat indicators from
  various open-source intelligence feeds. By enriching OCSF-formatted security
  events with threat intelligence data, analysts can quickly identify malicious
  activity and prioritize incident response efforts.

categories:
- contexts

inputs:
  osint-input-topic:
    name: OCSF OSINT Inventory Info topic
    description: |
      The topic to subscribe to and extract OSINT Inventory Info events.
    default: ocsf
  enrich-input-topic:
    name: Enrichment input topic
    description: |
      The topic to subscribe to and enrich with OSINT objects.
    default: ocsf
  enrich-output-topic:
    name: Enrichment output topic
    description: |
      The topic to publish to after having enriched OCSF events with OSINT
      objects.
    default: ocsf-osint
  max-ioc-age:
    name: Maximum age of an OCSF OSINT entry
    description: |
      The maximum age of an entry in the OCSF OSINT lookup table before it
      is automatically evicted.
    default: 30d

contexts:
  ocsf-osint:
    type: lookup-table
    description: |
      A lookup table that maps IOC values to [OCSF
      OSINT](https://schema.ocsf.io/1.5.0/objects/osint) objects.
