id: nxlog
name: NXLog
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/nxlog/package.svg

description: |
  [NXLog](https://nxlog.co) is a cross-platform log management solution that collects, parses, and forwards logs from various sources using a modular architecture. It supports a wide range of input and output modules, enabling seamless integration with different log sources and destinations across Windows, Linux, and other platforms.

  This package provides examples to receive and process NXLog data in JSON format via TCP or TLS connections, making it easy to centralize log collection from distributed NXLog agents.

