id: ocsf-trimming
name: OCSF Trimming
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/ocsf-trimming/package.svg

description: |
  Reduces the size of OCSF events by trimming optional and recommended fields
  based on configurable size settings. Supports three trimming levels:
  - S (Small): removes optional and recommended fields
  - M (Medium): removes optional fields only
  - L (Large): keeps all fields and derives string fields for enum fields

inputs:
  input-topic:
    name: Input topic
    description: Topic to subscribe to for OCSF events
    default: ocsf
  output-topic:
    name: Output topic
    description: Topic to publish trimmed OCSF events to
    default: ocsf-trimmed
  size:
    name: Size
    description: Must be one of S, M or L.
    default: M

pipelines:
  onboard-from-url:
    name: OCSF Event Trimming Pipeline
    description: |
      Subscribes to OCSF events from the input topic, applies size-based
      trimming to reduce event size, optionally derives additional context
      for large events, and publishes the results to the output topic.
    definition: |
      let $size_S = {drop_optional: true, drop_recommended: true}
      let $size_M = {drop_optional: true, drop_recommended: false}
      let $size_L = {drop_optional: false, drop_recommended: false}
      let $size = $size_{{ inputs.size }}
      let $is_large = not $size.drop_optional

      subscribe "{{ inputs.input-topic }}"
      ocsf::trim drop_optional=$size.drop_optional,
        drop_recommended=$size.drop_recommended
      if $is_large {
        ocsf::derive
      }
      publish "{{ inputs.output-topic }}"
