id: ocsf-trimming
name: OCSF Trimming
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/.tenzir.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/ocsf-trimming/package.svg

description: |
  Reduces the size of OCSF events by trimming optional and recommended fields
  based on configurable size settings. Supports three trimming levels:
  - S (Small): removes optional and recommended fields
  - M (Medium): removes optional fields only
  - L (Large): keeps all fields and derives string fields for enum fields

inputs:
  input-topic:
    name: Input topic
    description: Topic to subscribe to for OCSF events
    default: ocsf
  output-topic:
    name: Output topic
    description: Topic to publish trimmed OCSF events to
    default: ocsf-trimmed
  size:
    name: Size
    description: Must be one of S, M or L.
    default: M
