id: feodo
name: Feodo Abuse Blocklist
author: Tenzir
author_icon: https://github.com/tenzir.png
package_icon: https://raw.githubusercontent.com/tenzir/library/main/feodo/package.png

description: |
  Feodo Tracker is a project of abuse.ch with the goal of sharing botnet C&C
  servers associated with Dridex, Emotet (aka Heodo), TrickBot, QakBot (aka
  QuakBot / Qbot) and BazarLoader (aka BazarBackdoor). It offers various
  blocklists, helping network owners to protect their users from Dridex and
  Emotet/Heodo.

contexts:
  feodo:
    type: lookup-table
    description: A table that contains the elements of the feodo IP blocklist.

pipelines:
  update-context:
    name: Update Feodo Context
    description: A pipeline that periodically refreshes the Feodo lookup-table context.
    definition: |
      every 1 hour
        from https://feodotracker.abuse.ch/downloads/ipblocklist_aggressive.csv read csv --allow-comments
        | context update feodo --key=dst_ip --clear
    restart-on-error: 1 hour

snippets:
  - name: Lookup Feodo
    description: Evaluate all stored data with a `src_ip` field against the Feodo IP Blocklist.
    definition: |
      lookup feodo --field=dst_ip

  - name: Enrich Feodo
    description: Evaluate the `src_ip` field of the input data against the Feodo IP Blocklist.
    definition: |
      export | enrich feodo --field=dst_ip

  - name: Feodo Table Entries
    description: A gauge that shows the number of entries in the Feodo IP Blocklist lookup-table.
    definition: |
      show contexts | where name == "feodo" | chart gauge --value=num_entries
