id: feodo
name: Feodo Abuse Blocklist
author: Tenzir
author_icon: https://raw.githubusercontent.com/tenzir/library/main/author.svg
package_icon: https://raw.githubusercontent.com/tenzir/library/main/feodo/package.svg

description: |
  [Feodo Tracker](https://feodotracker.abuse.ch/) is a project of abuse.ch with
  the goal of sharing botnet C&C servers associated with Dridex, Emotet (aka
  Heodo), TrickBot, QakBot (aka QuakBot / Qbot) and BazarLoader (aka
  BazarBackdoor). It offers various blocklists, helping network owners to
  protect their users from Dridex and Emotet/Heodo.
categories:
- contexts

contexts:
  feodo:
    type: lookup-table
    description: A table that contains the elements of the feodo IP blocklist.

pipelines:
  update-context:
    name: Update Feodo Context
    description: A pipeline that periodically refreshes the Feodo lookup-table context.
    definition: |
      // tql2
      every 1h {
        load_http "https://feodotracker.abuse.ch/downloads/ipblocklist_aggressive.csv"
        read_csv comments=true
      }
      context::update "feodo", key="dst_ip"
    restart-on-error: 1h

examples:
  - name: Enrich Feodo
    description: Evaluate the `src_ip` field of the input data against the Feodo IP Blocklist.
    definition: |
      // tql2
      export
      context::enrich "feodo", key=dst_ip
